### ISSUE TITLE
Please, translate (at least) web site to English

### ISSUE THREAD

**Issue by q2dg** [linuxmuster/linuxmuster-webui#8]
It's a pity that non-german users can't enjoy this piece of software.
Thanks!

**Comment by netzint** [comment]
you can easily sign in as "root" and change the language.

**Comment by q2dg** [comment]
Yes, there is an "English" link which takes me to http://www.linuxmuster.net/en/start/. But text is in german anyway

**Comment by ironiemix** [comment]
The translation for the homepage is prepared, but not ready yet. Sorry for that. Feel free to ask all your questions on https://ask.linuxmuster.net/c/english we will do our best to help you out.

Usage of the system is possible in english as well as in german, only promotion and documentation lacks complete translation.

**Comment by netzint** [comment]
Thanks @ironiemix for the explanation and approval of the support.

Ticket closed.

**Comment by zefanja** [comment]
@q2dg Translation is done for most parts of the website. Let us know if you need any help. The forum is a good place to ask your questions :)
